services:

  postgres:
    image: postgres:18-alpine
    container_name: medicompare-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: medicompare
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql
    ports:
      - "5432:5432"

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: medicompare-server
    container_name: medicompare-server
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/medicompare
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      OPENROUTER_API_KEY: ${OPENROUTER_API_KEY}
    ports:
      - "8080:8080"

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: medicompare-client
    container_name: medicompare-client
    restart: unless-stopped
    depends_on:
      - server
    ports:
      - "3000:80"

volumes:
  postgres_data: