services:
  - type: web
    name: medicompare-ai
    runtime: docker
    repo: https://github.com/ganeshkumarbuilds/medicompare-ai
    dockerfilePath: ./server/Dockerfile
    dockerContext: ./server
    plan: free
    healthCheckPath: /api/hello
    envVars:
      - key: SPRING_DATASOURCE_URL
        sync: false
      - key: SPRING_DATASOURCE_USERNAME
        sync: false
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: OPENROUTER_API_KEY
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: FRONTEND_URL
        value: https://client-iota-one-53.vercel.app
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_APP_PASSWORD
        sync: false
      - key: ADMIN_DEFAULT_EMAIL
        sync: false
      - key: ADMIN_DEFAULT_PASSWORD
        sync: false
